define(
		[
			'app/main/mainController',
			'app/home/homeController',
			'app/logAcao/logAcaoController',
			'app/processo/processoController',
			'app/quadroProcessos/quadroProcessosController'
		]
);