define(
		[
			'app/auth/authResource',
			'app/info/infoResource',
			'app/logAcao/logAcaoResource',
			'app/usuarioTBG/usuarioTBGResource',
			'app/acao/acaoResource',
			'app/processo/processoResource'
		]
);